---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pull
  namespace: cqa
spec:
  steps:
    - args:
        - '-y'
        - install
        - git
      command: /usr/bin/dnf
      image: registry.redhat.io/ubi8/ubi:latest
    - args:
        - pull
      command: /usr/bin/git
      image: registry.redhat.io/ubi8/ubi:latest
  workspaces:
    - name: sources
      mountPath: /home/jboss/sources
