---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven
  namespace: cqa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '4Gi'
  volumeMode: Filesystem
