---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: target
  namespace: cqa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '256Mi'
  volumeMode: Filesystem
