---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: camel-quarkus-tests
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: project.openshift.io/v1
      kind: Project
  destinations:
    - server: 'https://api.ocp.eklexis.org:6443'
  sourceRepos:
    - 'https://github.com/agbaroni/camel-quarkus-application.git'
